### ISSUE TITLE
Adding number of counts to PETSIRD?

### ISSUE THREAD

**Issue by Imraj-Singh** [ETSInitiative/PRDdefinition#17]
The question is best seated when seeing the code for reading PRD with python:
https://github.com/ETSIhackers/LMSimRecon/blob/dca594d6a084c239875bb1ea3f38d41def5eb499/python/prd_io.py#L151

First, thanks Georg for developing this more!

At present we are appending. We talked about it briefly (I can't remember quite who it was), but we did say this is rather slow...

I was wondering if it is worth adding a total number of counts for each time block to PETSIRD? It would mean we could instantiate arrays of the right size/type. I guess it could help with some basic checks that the stream was read in correctly, or even if the time-block could fit in memory?

Just a thought and I guess this thinking think may be at odds with streaming to begin with... But on the otherhand I guess a single time block is the minimal amount we may want to reconstruct alone?

Also this is more of a python problem as with C++ we'd have a dynamic array I guess?

**Comment by KrisThielemans** [comment]
The PETSIRD examples shows you can get prompt-counts per timeblock 
https://github.com/ETSInitiative/PRDdefinition/blob/f8a26f8201a3375b961aeb01d4e80d32a02e5691/python/prd_analysis.py#L24
https://github.com/ETSInitiative/PRDdefinition/blob/f8a26f8201a3375b961aeb01d4e80d32a02e5691/cpp/prd_analysis.cpp#L53
I think this can be closed therefore.

**Comment by Imraj-Singh** [comment]
ah right thanks!
